### ISSUE TITLE
We shouldn't be linking/using SDL

### ISSUE THREAD

**Issue by shakesoda** [excessive/lua-bgfx#1]
SDL is great and all, but we shouldn't need to be doing that.

Need a way to get WMI info for BGFX without creating our own windows / linking more libs.

**Comment by JomerDev** [comment]
How do you want to create a window without any lib, if I may ask?

**Comment by shakesoda** [comment]
The idea was to rely on love's copy of SDL instead of bringing in a new one.

**Comment by JomerDev** [comment]
Ah. So you want to use loves window without using loves rendering.

**Comment by shakesoda** [comment]
yeah, and it'd go a long way for allowing this to be used with things that aren't SDL.

**Comment by JomerDev** [comment]
So you want it to use loves/sdls window if it is there, if not it should use something else? If I'm understaning you correctly

**Comment by shakesoda** [comment]
I want to be able to attach BGFX to any native window available, but love doesn't provide an API for getting the window data to make this possible.

**Comment by JomerDev** [comment]
Ah. I may be able to help you using SDL/loves window, if you need any help that is. I'm working on a library allowing multiple windows with love right now, so I know how you can get loves window

**Comment by shakesoda** [comment]
fixed (ish), now gets whatever current SDL window is active. in the future I'd like a way to pass just native handles, but this at least takes the window creation out.
